import type { Metadata } from "next";
import { Inter, Noto_Sans_SC, Urbanist } from "next/font/google";
import "./globals.css";
import { Header } from "./$components/header";
import { ChildrenProps } from "@/types";
import { PrelineInit } from "./$components/preline-init";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const noto = Noto_Sans_SC({
  preload: false,
  variable: "--font-noto",
});

const urbanist = Urbanist({ subsets: ["latin"], variable: "--font-urbanist" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<ChildrenProps>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${noto.variable} ${urbanist.variable} font-body`}
      >
        <PrelineInit>
          <main>
            <Header></Header>
            {children}
          </main>
        </PrelineInit>
      </body>
    </html>
  );
}
